#!/usr/bin/env node
/**
 * Fetch KanjiVG stroke-order SVG data for every kana in Unit 1 and emit
 * src/data/kanjivg.js — a static map of { char → [svgPathString, ...] }.
 *
 * KanjiVG is CC BY-SA 3.0: https://kanjivg.tagaini.net
 * Run once (or whenever new kana are added): node scripts/fetch-kanjivg.mjs
 */

import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dir, "..");

// Kana that need stroke data — every kana item in the curriculum must have an
// entry (the content contract hard-errors otherwise). Grows as units ship.
//   base 46 hiragana (Units 1-2) + 25 dakuten/handakuten (Unit 3).
const HIRAGANA = "あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん";
const DAKUTEN = "がぎぐげござじずぜぞだぢづでどばびぶべぼぱぴぷぺぽ";
const kanaChars = (HIRAGANA + DAKUTEN).split("");

console.log(`Fetching KanjiVG data for ${kanaChars.length} kana: ${kanaChars.join(" ")}\n`);

const result = {};

for (const char of kanaChars) {
  const cp = char.codePointAt(0).toString(16).padStart(5, "0");
  const url = `https://raw.githubusercontent.com/KanjiVG/kanjivg/master/kanji/${cp}.svg`;

  process.stdout.write(`  ${char} (${cp})  `);
  try {
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const svg = await res.text();

    // Extract path d= attributes in stroke order (id ends with -s1, -s2, ...)
    const paths = [];
    const re = /id="kvg:[^"]*-s\d+"[^>]*d="([^"]+)"/g;
    let m;
    while ((m = re.exec(svg)) !== null) paths.push(m[1]);

    if (paths.length === 0) throw new Error("no strokes found");
    result[char] = paths;
    console.log(`${paths.length} strokes`);
  } catch (err) {
    console.log(`ERROR: ${err.message}`);
  }
}

// Emit JS module
const lines = [
  "// Auto-generated by scripts/fetch-kanjivg.mjs — do not edit by hand.",
  "// KanjiVG CC BY-SA 3.0 https://kanjivg.tagaini.net",
  "// Stroke paths are in 109×109 SVG coordinate space.",
  "export const KANJIVG = {",
];
for (const [char, paths] of Object.entries(result)) {
  lines.push(`  "${char}": [`);
  for (const p of paths) lines.push(`    "${p}",`);
  lines.push(`  ],`);
}
lines.push("};");

const out = join(ROOT, "src", "data", "kanjivg.js");
writeFileSync(out, lines.join("\n") + "\n");
console.log(`\nWrote ${out}`);
